### ISSUE TITLE
conversion checklist

### ISSUE THREAD

**Issue by mrdwab** [mrdwab/splitstackshape#27]
Check for update/compatibility with `cSplit` and replace where possible.
- [x] `concat.split.compact`
- [x] `concat.split.expanded`
- [x] `concat.split.list`
- [x] `concat.split.multiple`

Other work:
- [x] Create aliases for `concat.split.expanded` and `concat.split.list`.
- [x] Include `concat.split.DT` (https://gist.github.com/mrdwab/6873058).
- [x] Include `stratified` (https://gist.github.com/mrdwab/933ffeaa7a1d718bd10a).
- [x] Move `vGrep` out as a non-exported function since it is used in a couple of places.
- [x] `getanID` needs to be made more robust.
- [x] Check to make sure that we are not overwriting existing `data.table`s (by reference) when we use `:=`. Something like `if (!is.data.table(dataset)) dataset <- as.data.table(dataset) else dataset <- copy(dataset)` might be safer.

Explore:
- [x] Can the `id.vars` be made redundant?
- [x] <s>Can `cSplit` be modified to accept vectors as its input?</s> Don't see an obvious way...
- [x] Are there utilities that can be brought in from my other packages (`expandRows`, for example)?
